// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5o8Uz6-FZqSL0hoUymyZTpKWQufKQk1o',
    appId: '1:664771475503:web:b9a8586fe49020d44e6eda',
    messagingSenderId: '664771475503',
    projectId: 'eisocomm-37fc9',
    authDomain: 'eisocomm-37fc9.firebaseapp.com',
    storageBucket: 'eisocomm-37fc9.firebasestorage.app',
    measurementId: 'G-JTNL2TQ0P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzSPJgUb_V45KLVhCPxKr6awRi5hSj3cY',
    appId: '1:664771475503:android:9b97dab4b2e0de7f4e6eda',
    messagingSenderId: '664771475503',
    projectId: 'eisocomm-37fc9',
    storageBucket: 'eisocomm-37fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCthuwOksvy1NSHOFUvtsgNgCvsS5E8IUo',
    appId: '1:664771475503:ios:a36ac5f973553b354e6eda',
    messagingSenderId: '664771475503',
    projectId: 'eisocomm-37fc9',
    storageBucket: 'eisocomm-37fc9.firebasestorage.app',
    iosBundleId: 'com.example.eIsocomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCthuwOksvy1NSHOFUvtsgNgCvsS5E8IUo',
    appId: '1:664771475503:ios:a36ac5f973553b354e6eda',
    messagingSenderId: '664771475503',
    projectId: 'eisocomm-37fc9',
    storageBucket: 'eisocomm-37fc9.firebasestorage.app',
    iosBundleId: 'com.example.eIsocomm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5o8Uz6-FZqSL0hoUymyZTpKWQufKQk1o',
    appId: '1:664771475503:web:69aab1cd5bc4a93e4e6eda',
    messagingSenderId: '664771475503',
    projectId: 'eisocomm-37fc9',
    authDomain: 'eisocomm-37fc9.firebaseapp.com',
    storageBucket: 'eisocomm-37fc9.firebasestorage.app',
    measurementId: 'G-0JMGH2X9R5',
  );

}